Add TODO regarding a need to replace Bundle
This is due to Bundle(for: ) as it is not implemented on the Swift
open source project as of 7/5/2019. This can be seen by running
`swift test` from inside the ./Stork directory. Producing this output:

```
Fatal error: init(for:) is not yet implemented
```